FROM php:8.2-apache

# Add composer to build image.
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Copy php installer script
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin

# Rrun php installer to install additional exentsions
RUN install-php-extensions gd ctype curl dom fileinfo filter hash mbstring openssl pcre pdo session tokenizer xml zip pdo_mysql bcmath

# Create user
RUN adduser reijo --disabled-password --disabled-login --gecos ""

# Copy envvars config
COPY ./config/envvars /etc/apache2/envvars

# Copy apache config
COPY ./config/apache2.conf /etc/apache2/apache2.conf

# Copy envvars config
COPY ./config/ports.conf /etc/apache2/ports.conf

# Copy vhost configuration
COPY ./vhost/*.conf /etc/apache2/sites-available/

# Copy system control.
COPY ./config/sysctl.conf /etc/

# Enable vhost
RUN a2ensite trade.conf

# Disable default vhost
RUN a2dissite 000-default.conf

# Change ownership
RUN chown reijo:reijo -R /var/www/*

# Enable apache mod rewrite
RUN a2enmod rewrite headers
