export const CHART_WATCHLIST_REQUEST = 'CHART_WATCHLIST_REQUEST';
export const CHART_WATCHLIST_SUCCESS = 'CHART_WATCHLIST_SUCCESS';
export const CHART_WATCHLIST_FAILURE = 'CHART_WATCHLIST_FAILURE';

export const CHART_AVERAGE_REQUEST = 'CHART_AVERAGE_REQUEST';
export const CHART_AVERAGE_SUCCESS = 'CHART_AVERAGE_SUCCESS';
export const CHART_AVERAGE_FAILURE = 'CHART_AVERAGE_FAILURE';

export const CHART_FETCH_REQUEST = 'CHART_FETCH_REQUEST';
export const CHART_FETCH_SUCCESS = 'CHART_FETCH_SUCCESS';
export const CHART_FETCH_FAILURE = 'CHART_FETCH_FAILURE';
