export const DASHBOARD_START_REQUEST = "DASHBOARD_START_REQUEST";
export const DASHBOARD_START_SUCCESS = "DASHBOARD_START_SUCCESS";
export const DASHBOARD_START_FAILURE = "DASHBOARD_START_FAILURE";

export const DASHBOARD_PRICE_REQUEST = "DASHBOARD_PRICE_REQUEST";
export const DASHBOARD_PRICE_SUCCESS = "DASHBOARD_PRICE_SUCCESS";
export const DASHBOARD_PRICE_FAILURE = "DASHBOARD_PRICE_FAILURE";

export const DASHBOARD_REPORT_REQUEST = "DASHBOARD_REPORT_REQUEST";
export const DASHBOARD_REPORT_SUCCESS = "DASHBOARD_REPORT_SUCCESS";
export const DASHBOARD_REPORT_FAILURE = "DASHBOARD_REPORT_FAILURE";

export const DASHBOARD_DIVIDEND_REQUEST = "DASHBOARD_DIVIDEND_REQUEST";
export const DASHBOARD_DIVIDEND_SUCCESS = "DASHBOARD_DIVIDEND_SUCCESS";
export const DASHBOARD_DIVIDEND_FAILURE = "DASHBOARD_DIVIDEND_FAILURE";

export const DASHBOARD_SECTOR_REQUEST = "DASHBOARD_SECTOR_REQUEST";
export const DASHBOARD_SECTOR_SUCCESS = "DASHBOARD_SECTOR_SUCCESS";
export const DASHBOARD_SECTOR_FAILURE = "DASHBOARD_SECTOR_FAILURE";

export const DASHBOARD_LIST_REQUEST = "DASHBOARD_LIST_REQUEST";
export const DASHBOARD_LIST_SUCCESS = "DASHBOARD_LIST_SUCCESS";
export const DASHBOARD_LIST_FAILURE = "DASHBOARD_LIST_FAILURE";

export const DASHBOARD_BLUE_REQUEST = "DASHBOARD_BLUE_REQUEST";
export const DASHBOARD_BLUE_SUCCESS = "DASHBOARD_BLUE_SUCCESS";
export const DASHBOARD_BLUE_FAILURE = "DASHBOARD_BLUE_FAILURE";

export const DASHBOARD_BLUE_STORE_REQUEST = "DASHBOARD_BLUE_STORE_REQUEST";
export const DASHBOARD_BLUE_STORE_SUCCESS = "DASHBOARD_BLUE_STORE_SUCCESS";
export const DASHBOARD_BLUE_STORE_FAILURE = "DASHBOARD_BLUE_STORE_FAILURE";

export const DASHBOARD_BLUE_DESTROY_REQUEST = "DASHBOARD_BLUE_DESTROY_REQUEST";
export const DASHBOARD_BLUE_DESTROY_SUCCESS = "DASHBOARD_BLUE_DESTROY_SUCCESS";
export const DASHBOARD_BLUE_DESTROY_FAILURE = "DASHBOARD_BLUE_DESTROY_FAILURE";

export const DASHBOARD_EDGE_REQUEST = "DASHBOARD_EDGE_REQUEST";
export const DASHBOARD_EDGE_SUCCESS = "DASHBOARD_EDGE_SUCCESS";
export const DASHBOARD_EDGE_FAILURE = "DASHBOARD_EDGE_FAILURE";

export const DASHBOARD_EDGE_UPDATE_REQUEST = "DASHBOARD_EDGE_UPDATE_REQUEST";
export const DASHBOARD_EDGE_UPDATE_SUCCESS = "DASHBOARD_EDGE_UPDATE_SUCCESS";
export const DASHBOARD_EDGE_UPDATE_FAILURE = "DASHBOARD_EDGE_UPDATE_FAILURE";
