export const STOCK_EXPLORER_FETCH_REQUEST = 'STOCK_EXPLORER_FETCH_REQUEST';
export const STOCK_EXPLORER_FETCH_SUCCESS = 'STOCK_EXPLORER_FETCH_SUCCESS';
export const STOCK_EXPLORER_FETCH_FAILURE = 'STOCK_EXPLORER_FETCH_FAILURE';
