export const STOCK_PORTFOLIO_FETCH_REQUEST = 'STOCK_PORTFOLIO_FETCH_REQUEST';
export const STOCK_PORTFOLIO_FETCH_SUCCESS = 'STOCK_PORTFOLIO_FETCH_SUCCESS';
export const STOCK_PORTFOLIO_FETCH_FAILURE = 'STOCK_PORTFOLIO_FETCH_FAILURE';

export const STOCK_PORTFOLIO_STORE_REQUEST = 'STOCK_PORTFOLIO_STORE_REQUEST';
export const STOCK_PORTFOLIO_STORE_SUCCESS = 'STOCK_PORTFOLIO_STORE_SUCCESS';
export const STOCK_PORTFOLIO_STORE_FAILURE = 'STOCK_PORTFOLIO_STORE_FAILURE';

export const STOCK_PORTFOLIO_UPDATE_REQUEST = 'STOCK_PORTFOLIO_UPDATE_REQUEST';
export const STOCK_PORTFOLIO_UPDATE_SUCCESS = 'STOCK_PORTFOLIO_UPDATE_SUCCESS';
export const STOCK_PORTFOLIO_UPDATE_FAILURE = 'STOCK_PORTFOLIO_UPDATE_FAILURE';

export const STOCK_PORTFOLIO_DESTROY_REQUEST = 'STOCK_PORTFOLIO_DESTROY_REQUEST';
export const STOCK_PORTFOLIO_DESTROY_SUCCESS = 'STOCK_PORTFOLIO_DESTROY_SUCCESS';
export const STOCK_PORTFOLIO_DESTROY_FAILURE = 'STOCK_PORTFOLIO_DESTROY_FAILURE';
