export const STOCK_PORTFOLIO_FETCH_REQUEST = 'STOCK_PORTFOLIO_FETCH_REQUEST';
export const STOCK_PORTFOLIO_FETCH_SUCCESS = 'STOCK_PORTFOLIO_FETCH_SUCCESS';
export const STOCK_PORTFOLIO_FETCH_FAILURE = 'STOCK_PORTFOLIO_FETCH_FAILURE';

export const STOCK_PORTFOLIO_STORE_REQUEST = 'STOCK_PORTFOLIO_STORE_REQUEST';
export const STOCK_PORTFOLIO_STORE_SUCCESS = 'STOCK_PORTFOLIO_STORE_SUCCESS';
export const STOCK_PORTFOLIO_STORE_FAILURE = 'STOCK_PORTFOLIO_STORE_FAILURE';
