export const STOCK_START_REQUEST = "STOCK_START_REQUEST";
export const STOCK_START_SUCCESS = "STOCK_START_SUCCESS";
export const STOCK_START_FAILURE = "STOCK_START_FAILURE";

export const STOCK_PRICE_REQUEST = "STOCK_PRICE_REQUEST";
export const STOCK_PRICE_SUCCESS = "STOCK_PRICE_SUCCESS";
export const STOCK_PRICE_FAILURE = "STOCK_PRICE_FAILURE";

export const STOCK_REPORT_REQUEST = "STOCK_REPORT_REQUEST";
export const STOCK_REPORT_SUCCESS = "STOCK_REPORT_SUCCESS";
export const STOCK_REPORT_FAILURE = "STOCK_REPORT_FAILURE";

export const STOCK_DIVIDEND_REQUEST = "STOCK_DIVIDEND_REQUEST";
export const STOCK_DIVIDEND_SUCCESS = "STOCK_DIVIDEND_SUCCESS";
export const STOCK_DIVIDEND_FAILURE = "STOCK_DIVIDEND_FAILURE";

export const STOCK_SECTOR_REQUEST = "STOCK_SECTOR_REQUEST";
export const STOCK_SECTOR_SUCCESS = "STOCK_SECTOR_SUCCESS";
export const STOCK_SECTOR_FAILURE = "STOCK_SECTOR_FAILURE";

export const STOCK_BLUE_REQUEST = "STOCK_BLUE_REQUEST";
export const STOCK_BLUE_SUCCESS = "STOCK_BLUE_SUCCESS";
export const STOCK_BLUE_FAILURE = "STOCK_BLUE_FAILURE";

export const STOCK_COMMON_REQUEST = "STOCK_COMMON_REQUEST";
export const STOCK_COMMON_SUCCESS = "STOCK_COMMON_SUCCESS";
export const STOCK_COMMON_FAILURE = "STOCK_COMMON_FAILURE";

export const STOCK_WATCH_BUILD_REQUEST = "STOCK_WATCH_BUILD_REQUEST";
export const STOCK_WATCH_BUILD_SUCCESS = "STOCK_WATCH_BUILD_SUCCESS";
export const STOCK_WATCH_BUILD_FAILURE = "STOCK_WATCH_BUILD_FAILURE";

export const STOCK_WATCH_STORE_REQUEST = "STOCK_WATCH_STORE_REQUEST";
export const STOCK_WATCH_STORE_SUCCESS = "STOCK_WATCH_STORE_SUCCESS";
export const STOCK_WATCH_STORE_FAILURE = "STOCK_WATCH_STORE_FAILURE";
