export const STOCK_START_REQUEST = "STOCK_START_REQUEST";
export const STOCK_START_SUCCESS = "STOCK_START_SUCCESS";
export const STOCK_START_FAILURE = "STOCK_START_FAILURE";

export const STOCK_PRICE_REQUEST = "STOCK_PRICE_REQUEST";
export const STOCK_PRICE_SUCCESS = "STOCK_PRICE_SUCCESS";
export const STOCK_PRICE_FAILURE = "STOCK_PRICE_FAILURE";

export const STOCK_REPORT_REQUEST = "STOCK_REPORT_REQUEST";
export const STOCK_REPORT_SUCCESS = "STOCK_REPORT_SUCCESS";
export const STOCK_REPORT_FAILURE = "STOCK_REPORT_FAILURE";

export const STOCK_DIVIDEND_REQUEST = "STOCK_DIVIDEND_REQUEST";
export const STOCK_DIVIDEND_SUCCESS = "STOCK_DIVIDEND_SUCCESS";
export const STOCK_DIVIDEND_FAILURE = "STOCK_DIVIDEND_FAILURE";

export const STOCK_SECTOR_REQUEST = "STOCK_SECTOR_REQUEST";
export const STOCK_SECTOR_SUCCESS = "STOCK_SECTOR_SUCCESS";
export const STOCK_SECTOR_FAILURE = "STOCK_SECTOR_FAILURE";
