export const STOCK_TRADE_BLUECHIP_REQUEST = 'STOCK_TRADE_BLUECHIP_REQUEST';
export const STOCK_TRADE_BLUECHIP_SUCCESS = 'STOCK_TRADE_BLUECHIP_SUCCESS';
export const STOCK_TRADE_BLUECHIP_FAILURE = 'STOCK_TRADE_BLUECHIP_FAILURE';

export const STOCK_TRADE_COMMON_REQUEST = 'STOCK_TRADE_COMMON_REQUEST';
export const STOCK_TRADE_COMMON_SUCCESS = 'STOCK_TRADE_COMMON_SUCCESS';
export const STOCK_TRADE_COMMON_FAILURE = 'STOCK_TRADE_COMMON_FAILURE';

export const STOCK_TRADE_STORE_REQUEST = 'STOCK_TRADE_STORE_REQUEST';
export const STOCK_TRADE_STORE_SUCCESS = 'STOCK_TRADE_STORE_SUCCESS';
export const STOCK_TRADE_STORE_FAILURE = 'STOCK_TRADE_STORE_FAILURE';

export const STOCK_TRADE_DESTROY_REQUEST = 'STOCK_TRADE_DESTROY_REQUEST';
export const STOCK_TRADE_DESTROY_SUCCESS = 'STOCK_TRADE_DESTROY_SUCCESS';
export const STOCK_TRADE_DESTROY_FAILURE = 'STOCK_TRADE_DESTROY_FAILURE';
