export const TRADE_BLUECHIP_REQUEST = 'TRADE_BLUECHIP_REQUEST'
export const TRADE_BLUECHIP_SUCCESS = 'TRADE_BLUECHIP_SUCCESS'
export const TRADE_BLUECHIP_FAILURE = 'TRADE_BLUECHIP_FAILURE'

export const TRADE_COMMON_REQUEST = 'TRADE_COMMON_REQUEST'
export const TRADE_COMMON_SUCCESS = 'TRADE_COMMON_SUCCESS'
export const TRADE_COMMON_FAILURE = 'TRADE_COMMON_FAILURE'

export const TRADE_STORE_REQUEST = 'TRADE_STORE_REQUEST'
export const TRADE_STORE_SUCCESS = 'TRADE_STORE_SUCCESS'
export const TRADE_STORE_FAILURE = 'TRADE_STORE_FAILURE'

export const TRADE_DESTROY_REQUEST = 'TRADE_DESTROY_REQUEST'
export const TRADE_DESTROY_SUCCESS = 'TRADE_DESTROY_SUCCESS'
export const TRADE_DESTROY_FAILURE = 'TRADE_DESTROY_FAILURE'
