export const USER_CREDENTIAL_REQUEST = "USER_CREDENTIAL_REQUEST";
export const USER_CREDENTIAL_SUCCESS = "USER_CREDENTIAL_SUCCESS";
export const USER_CREDENTIAL_FAILURE = "USER_CREDENTIAL_FAILURE";
export const USER_CREDENTIAL_RESET = "USER_CREDENTIAL_RESET";
