export const WATCHLIST_BUILD_REQUEST = 'WATCHLIST_BUILD_REQUEST'
export const WATCHLIST_BUILD_SUCCESS = 'WATCHLIST_BUILD_SUCCESS'
export const WATCHLIST_BUILD_FAILURE = 'WATCHLIST_BUILD_FAILURE'

export const WATCHLIST_FETCH_REQUEST = 'WATCHLIST_FETCH_REQUEST'
export const WATCHLIST_FETCH_SUCCESS = 'WATCHLIST_FETCH_SUCCESS'
export const WATCHLIST_FETCH_FAILURE = 'WATCHLIST_FETCH_FAILURE'

export const WATCHLIST_STORE_REQUEST = 'WATCHLIST_STORE_REQUEST'
export const WATCHLIST_STORE_SUCCESS = 'WATCHLIST_STORE_SUCCESS'
export const WATCHLIST_STORE_FAILURE = 'WATCHLIST_STORE_FAILURE'

export const WATCHLIST_DESTROY_REQUEST = 'WATCHLIST_DESTROY_REQUEST'
export const WATCHLIST_DESTROY_SUCCESS = 'WATCHLIST_DESTROY_SUCCESS'
export const WATCHLIST_DESTROY_FAILURE = 'WATCHLIST_DESTROY_FAILURE'
